name: Deploy .NET Core API to Azure Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up .NET SDK
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0  # Make sure to use the correct version

    # Build the .NET project
    - name: Build project
      run: dotnet build ./beeInnovative/beeInnovative.csproj --configuration Release

    # Publish the .NET project for Azure Functions
    - name: Publish project
      run: dotnet publish ./beeInnovative/beeInnovative.csproj -c Release -o ./publish

    # Deploy to Azure Functions
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: repo-main  # Replace with your Azure Functions app name
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
        package: ./publish
